version: '2'

services:
    notebook:
        image: jupyter/minimal-notebook
        command: start-notebook.sh --NotebookApp.token=''
        ports:
            - "8888"

    proxy:
        image: discoenv/cas-proxy:master
        command:
            - "--backend-url"
            - http://notebook:8888
            - "--cas-base-url"
            - https://hana.iplantcollaborative.org/cas/
            - "--frontend-url"
            - http://192.168.1.11:8080
        ports:
            - "8080:8080"
        depends_on:
            - notebook
