apiVersion: apps/v1
kind: Deployment
metadata:
  name: vice-loading
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: vice-loading
  template:
    metadata:
      labels:
        de-app: vice-loading
    spec:
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: vice-loading.yaml
                path: local.yaml
      containers:
      - name: vice-loading
        image: discoenv/vice-loading
        imagePullPolicy: Always
        env:
          - name: NODE_CONFIG_DIR
            value: "./config:/etc/iplant/de"
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
          limits:
            cpu: "4000m"
            memory: "4Gi"
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 60000
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 60000
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vice-loading
spec:
  selector:
    de-app: vice-loading
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
