listen_port: 60000
vice_domain: https://not-a-real-domain-hopefully.com
db: postgres://user:password@host:port/database
ui: ../../client-landing/build
k8s_enabled: true
app_exposer:
  url: http://app-exposer